databases:
  - name: db
    databaseName: jwtapp
    user: postgres
    postgresMajorVersion: 14

services:
  - type: postgres
    name: db
    version: latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: jwtapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aidos2003
    volumes:
      - postgres_data:/var/lib/postgresql/data

  - type: docker
    name: salles
    buildCommand: docker build -t salles .
    startCommand: docker run -p 8080:8080 --env SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jwtapp --env SPRING_DATASOURCE_USERNAME=postgres --env SPRING_DATASOURCE_PASSWORD=aidos2003 --volume ./logs:/app/logs salles
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db:5432/jwtapp
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: aidos2003
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
